services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nestjs
      POSTGRES_USER: nestUser
      POSTGRES_PASSWORD: nestUser
    ports:
      - "5432:5432"
    volumes:
      - postgresData:/var/lib/postgresq

volumes:
  postgresData: